version: "3"

services:
  graph-koa:
    image: monkingxue/graph-koa:fake-redis
    depends_on:
      - redis
    environment:
      - PORT=3001
      - REDIS_HOST=redis
    ports:
      - '3001:3001'
    networks:
      - front-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379'
    networks:
      - front-tier

networks:
  front-tier: